name: CD Production
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Android application
        run: ./gradlew clean build
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: app/build/**/*.apk
  tag-release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"
      - name: Tag version
        run: |
          version=`cat ./.github/resources/APK_VERSION`
          git tag -a "v$version" -m "Release version $version"
      - name: Push tag to Github
        run: git push --tags origin