name: Integration
on:
  pull_request:
    branches: [ develop ]
    paths:
      - './**/*gradle*'
      - './**/*.kt*'
      - .github/workflows/integration.yml
  push:
    branches: [ develop ]
    paths:
      - './**/*gradle*'
      - './**/*.kt*'
      - .github/workflows/integration.yml
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build application
        run: ./gradlew :app:build